package co.com.touresbalon.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000281-redhat-3
 * 2018-09-30T17:04:49.115-05:00
 * Generated source version: 3.1.11.fuse-000281-redhat-3
 * 
 */
@WebService(targetNamespace = "http://service.touresbalon.com.co/", name = "OrdenesService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrdenesService {

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenesCerradasRequest", output = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenesCerradasResponse")
    @RequestWrapper(localName = "consultarOrdenesCerradas", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenesCerradas")
    @ResponseWrapper(localName = "consultarOrdenesCerradasResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenesCerradasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaOrden consultarOrdenesCerradas(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaOrden filtro
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/crearOrdenRequest", output = "http://service.touresbalon.com.co/OrdenesService/crearOrdenResponse")
    @RequestWrapper(localName = "crearOrden", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.CrearOrden")
    @ResponseWrapper(localName = "crearOrdenResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.CrearOrdenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoOrden crearOrden(
        @WebParam(name = "orden", targetNamespace = "")
        co.com.touresbalon.service.OrdenBO orden
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenesPorClienteRequest", output = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenesPorClienteResponse")
    @RequestWrapper(localName = "consultarOrdenesPorCliente", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenesPorCliente")
    @ResponseWrapper(localName = "consultarOrdenesPorClienteResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenesPorClienteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaOrden consultarOrdenesPorCliente(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaOrden filtro
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenPorNumeroProductoRequest", output = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenPorNumeroProductoResponse")
    @RequestWrapper(localName = "consultarOrdenPorNumeroProducto", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenPorNumeroProducto")
    @ResponseWrapper(localName = "consultarOrdenPorNumeroProductoResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenPorNumeroProductoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaOrden consultarOrdenPorNumeroProducto(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaOrden filtro
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/consultarNumeroOrdenesCerradasRequest", output = "http://service.touresbalon.com.co/OrdenesService/consultarNumeroOrdenesCerradasResponse")
    @RequestWrapper(localName = "consultarNumeroOrdenesCerradas", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarNumeroOrdenesCerradas")
    @ResponseWrapper(localName = "consultarNumeroOrdenesCerradasResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarNumeroOrdenesCerradasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaOrden consultarNumeroOrdenesCerradas(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaOrden filtro
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenPorNumeroRequest", output = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenPorNumeroResponse")
    @RequestWrapper(localName = "consultarOrdenPorNumero", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenPorNumero")
    @ResponseWrapper(localName = "consultarOrdenPorNumeroResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenPorNumeroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaOrden consultarOrdenPorNumero(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaOrden filtro
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/actualizarOrdenRequest", output = "http://service.touresbalon.com.co/OrdenesService/actualizarOrdenResponse")
    @RequestWrapper(localName = "actualizarOrden", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ActualizarOrden")
    @ResponseWrapper(localName = "actualizarOrdenResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ActualizarOrdenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoOrden actualizarOrden(
        @WebParam(name = "solicitudActualizacion", targetNamespace = "")
        co.com.touresbalon.service.SolicitudActualizacionOrden solicitudActualizacion
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenesAbiertasRequest", output = "http://service.touresbalon.com.co/OrdenesService/consultarOrdenesAbiertasResponse")
    @RequestWrapper(localName = "consultarOrdenesAbiertas", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenesAbiertas")
    @ResponseWrapper(localName = "consultarOrdenesAbiertasResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarOrdenesAbiertasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaOrden consultarOrdenesAbiertas(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaOrden filtro
    );

    @WebMethod
    @Action(input = "http://service.touresbalon.com.co/OrdenesService/actualizarStatusOrdenRequest", output = "http://service.touresbalon.com.co/OrdenesService/actualizarStatusOrdenResponse")
    @RequestWrapper(localName = "actualizarStatusOrden", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ActualizarStatusOrden")
    @ResponseWrapper(localName = "actualizarStatusOrdenResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ActualizarStatusOrdenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoOrden actualizarStatusOrden(
        @WebParam(name = "solicitudActualizacion", targetNamespace = "")
        co.com.touresbalon.service.SolicitudActualizacionOrden solicitudActualizacion
    );
}
