package co.com.touresbalon.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000281-redhat-3
 * 2018-09-30T17:04:49.268-05:00
 * Generated source version: 3.1.11.fuse-000281-redhat-3
 * 
 */
@WebServiceClient(name = "ServicioOrdenes", 
                  wsdlLocation = "file:/Users/arkazero/workspaceFuse11/OMS-Mod-Ordenes/src/main/resources/OrdenesService.wsdl",
                  targetNamespace = "http://service.touresbalon.com.co/") 
public class ServicioOrdenes extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.touresbalon.com.co/", "ServicioOrdenes");
    public final static QName OrdenesServicePort = new QName("http://service.touresbalon.com.co/", "OrdenesServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/arkazero/workspaceFuse11/OMS-Mod-Ordenes/src/main/resources/OrdenesService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioOrdenes.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/arkazero/workspaceFuse11/OMS-Mod-Ordenes/src/main/resources/OrdenesService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioOrdenes(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioOrdenes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioOrdenes() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServicioOrdenes(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioOrdenes(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioOrdenes(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrdenesService
     */
    @WebEndpoint(name = "OrdenesServicePort")
    public OrdenesService getOrdenesServicePort() {
        return super.getPort(OrdenesServicePort, OrdenesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrdenesService
     */
    @WebEndpoint(name = "OrdenesServicePort")
    public OrdenesService getOrdenesServicePort(WebServiceFeature... features) {
        return super.getPort(OrdenesServicePort, OrdenesService.class, features);
    }

}
